name: flutter_repository
description: A new Flutter package.
version: 1.0.0
author: Horoliuk Maksym <goroliuk.maksym@gmail.com>
homepage: https://github.com/gorolykmaxim/flutter_repository

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  class_test: ^1.0.0