name: flutter_repository
description: A new Flutter package.
version: 1.1.0
homepage: https://github.com/gorolykmaxim/flutter_repository

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mockito: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  class_test: ^1.0.0